services:
  # Backend API service
  - type: web
    name: flashcard-app-api
    env: node
    runtime: node:18.17.0
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    domains:
      - api.flashcard-app.onrender.com

  # Frontend static site
  - type: static
    name: flashcard-app-client
    env: static
    buildCommand: |
      cd client
      npm ci
      npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://api.flashcard-app.onrender.com/api
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    domains:
      - flashcard-app.onrender.com 